In [14]:
import numpy as np

a1 = np.array([np.array([3, 1, 4, 1]),
               np.array([5, 9, 2, 6]),
               np.array([5, 3, 5, 8])])

a2 = np.array([np.array([9, 7, 9, 3]),
               np.array([2, 3, 8, 4])])

a3 = np.array([np.array([3, 3, 8, 3]),
               np.array([2, 7, 9, 5]),
               np.array([0, 2, 8, 8]),
               np.array([6, 2, 6, 4])])

A = np.array([a1, a2, a3])

print("A =\n", A)
print("A =\n", A.T)

A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A =
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]


In [4]:
A1 = [record[-2:] for record in A]
A1 = np.array(A1)

print("A = \n", A)
print("A1 = \n", A1)

A = 
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A1 = 
 [[[5 9 2 6]
  [5 3 5 8]]

 [[9 7 9 3]
  [2 3 8 4]]

 [[0 2 8 8]
  [6 2 6 4]]]


In [17]:
pad_below1 = 4 - len(a1)
pad_below2 = 4 - len(a2)
pad_below3 = 4 - len(a3)

pad_above = 0
pad_left = 0
pad_right = 0

n_add = [((pad_above, pad_below1), (pad_left, pad_right)),
         ((pad_above, pad_below2), (pad_left, pad_right)),
         ((pad_above, pad_below3), (pad_left, pad_right)),]

A2 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A2 = np.array(A2)

print("A = \n", A)
print("A2 = \n", A2)
print("A2^T = \n", A2.T)

A = 
 [array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]])
 array([[9, 7, 9, 3],
       [2, 3, 8, 4]])
 array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])]
A2 = 
 [[[3 1 4 1]
  [5 9 2 6]
  [5 3 5 8]
  [0 0 0 0]]

 [[9 7 9 3]
  [2 3 8 4]
  [0 0 0 0]
  [0 0 0 0]]

 [[3 3 8 3]
  [2 7 9 5]
  [0 2 8 8]
  [6 2 6 4]]]
A2^T = 
 [[[3 9 3]
  [5 2 2]
  [5 0 0]
  [0 0 6]]

 [[1 7 3]
  [9 3 7]
  [3 0 2]
  [0 0 2]]

 [[4 9 8]
  [2 8 9]
  [5 0 8]
  [0 0 6]]

 [[1 3 3]
  [6 4 5]
  [8 0 8]
  [0 0 4]]]
