# 1.1 Getting Started

In [1]:
import torch as t

In [2]:
x = t.arange(12, dtype=t.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel() # the total number of elements

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
t.zeros((2,3,4)) # 3X4 2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
t.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
t.randn(3,4)

tensor([[ 0.2708, -0.8872,  0.8030,  2.0058],
        [ 0.0600, -0.0768,  0.7471, -1.7489],
        [-1.3051,  1.7861, -0.2287,  0.2567]])

In [10]:
t.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# 1.2 Operations

In [11]:
x = t.tensor([1.0, 2, 4, 8])
y = t.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
t.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
X = t.arange(12, dtype=t.float32).reshape((3,4))
Y = t.tensor([[2.,1,4,3],[1,2,3,4],[4,3,2,1]])
t.cat((X,Y),dim=0), t.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
X.sum()

tensor(66.)

# 1.3 Broadcasting Mechanism

In [19]:
a = t.arange(3).reshape((3,1))
b = t.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 1.4 Indexing and Slicing

In [22]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# 1.5 Saving Memory

In [31]:
before = id(Y)
print(id(Y))
Y = Y + X
print(id(Y))
Y, id(Y) == before

140534363168320
140534363191680


(tensor([[26., 25., 28., 27.],
         [25., 26., 27., 28.],
         [20., 21., 22., 23.]]),
 False)

In [30]:
Z = t.zeros_like(Y)
print(Z)
print('id(Z):', id(Z))
Z[:] = X+Y
print(Z)
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 140534363208512
tensor([[26., 25., 28., 27.],
        [25., 26., 27., 28.],
        [20., 21., 22., 23.]])
id(Z): 140534363208512


In [33]:
before = id(X)
X += Y
id(X)==before

True

# 1.6 Conversion to Other Python Objects

In [34]:
A = X.numpy()
B = t.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
a = t.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)